import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Post1 from "./posts/textWord";
import Login from "../components/Organism/Login";
import AutoLayout from "../components/Layouts/autoLayout";
import TextWord from "./posts/textWord";
import { Layout } from "../components/Layouts/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <TextWord />
        </Layout>
      </main>
    </>
  );
}
